[package]
name = "factorial-rs"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]

[lib]
name = "factorial_rs"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]
